import type { BookItem, HighlightItem } from "../types.js";

export const DEMO_BOOKS: BookItem[] = [
  {
    id: "book-1",
    asin: "B00ZUX90S4",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    highlightsCount: 6,
    tags: ["Software Architecture", "Distributed Systems", "Reliability"],
    status: "reading",
  },
  {
    id: "book-2",
    asin: "B01862ES3A",
    title: "The Daily Stoic",
    author: "Ryan Holiday",
    highlightsCount: 6,
    tags: ["Philosophy", "Stoicism", "Mindset"],
    status: "completed",
  },
  {
    id: "book-3",
    asin: "B07D23CFGR",
    title: "Atomic Habits",
    author: "James Clear",
    highlightsCount: 5,
    tags: ["Productivity", "Habit Formation", "Systems Thinking"],
    status: "completed",
  },
  {
    id: "book-4",
    asin: "B004J4XGN6",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    highlightsCount: 5,
    tags: ["Psychology", "Cognitive Biases", "Decision Making"],
    status: "reading",
  },
  {
    id: "book-5",
    asin: "B001GSTOAM",
    title: "Clean Code",
    author: "Robert C. Martin",
    highlightsCount: 4,
    tags: ["Software Craftsmanship", "Refactoring", "Clean Code"],
    status: "completed",
  },
];

export const DEMO_HIGHLIGHTS: HighlightItem[] = [
  // Designing Data-Intensive Applications
  {
    id: "hl-101",
    bookId: "book-1",
    bookTitle: "Designing Data-Intensive Applications",
    rawText: "Reliability means continuing to work correctly (performing the correct function at the desired level of performance) even in the face of adversity (hardware or software faults, and even human error).",
    location: 120,
    color: "yellow",
    importance: "Essential",
    tags: ["Reliability", "Software Architecture"],
    sourceNote: "Core definition of software reliability.",
    interpretation: "A system is not truly reliable if it only works under ideal conditions.",
  },
  {
    id: "hl-102",
    bookId: "book-1",
    bookTitle: "Designing Data-Intensive Applications",
    rawText: "Scalability is the term we use to describe a system's ability to cope with increased load.",
    location: 245,
    color: "blue",
    importance: "High",
    tags: ["Distributed Systems"],
  },
  {
    id: "hl-103",
    bookId: "book-1",
    bookTitle: "Designing Data-Intensive Applications",
    rawText: "Maintainability means many different people will work on the system over time, and they should all be able to work on it productively.",
    location: 380,
    color: "pink",
    importance: "High",
    tags: ["Clean Code", "Software Architecture"],
  },
  {
    id: "hl-104",
    bookId: "book-1",
    bookTitle: "Designing Data-Intensive Applications",
    rawText: "Behind every fault-tolerant system is a set of carefully reasoned invariants.",
    location: 512,
    color: "orange",
    importance: "Essential",
    tags: ["Distributed Systems"],
  },

  // The Daily Stoic
  {
    id: "hl-201",
    bookId: "book-2",
    bookTitle: "The Daily Stoic",
    rawText: "The chief task in life is simply this: to identify and separate matters so that I can say clearly to myself which are externals not under my control, and which have to do with the choices I actually control.",
    location: 45,
    color: "yellow",
    importance: "Essential",
    tags: ["Stoicism", "Mindset"],
    sourceNote: "Epictetus' Dichotomy of Control.",
    interpretation: "Direct energy only towards intentional choices, never external outcomes.",
  },
  {
    id: "hl-202",
    bookId: "book-2",
    bookTitle: "The Daily Stoic",
    rawText: "You have power over your mind - not outside events. Realize this, and you will find strength.",
    location: 190,
    color: "yellow",
    importance: "High",
    tags: ["Stoicism", "Psychology"],
  },
  {
    id: "hl-203",
    bookId: "book-2",
    bookTitle: "The Daily Stoic",
    rawText: "Waste no more time arguing what a good person should be. Be one.",
    location: 320,
    color: "pink",
    importance: "Essential",
    tags: ["Philosophy"],
  },

  // Atomic Habits
  {
    id: "hl-301",
    bookId: "book-3",
    bookTitle: "Atomic Habits",
    rawText: "You do not rise to the level of your goals. You fall to the level of your systems.",
    location: 110,
    color: "yellow",
    importance: "Essential",
    tags: ["Systems Thinking", "Habit Formation"],
    interpretation: "Focus on designing frictionless recurring routines rather than obsessing over end milestones.",
  },
  {
    id: "hl-302",
    bookId: "book-3",
    bookTitle: "Atomic Habits",
    rawText: "Every action you take is a vote for the type of person you wish to become.",
    location: 280,
    color: "orange",
    importance: "High",
    tags: ["Habit Formation", "Mindset"],
  },
  {
    id: "hl-303",
    bookId: "book-3",
    bookTitle: "Atomic Habits",
    rawText: "Make it obvious, make it attractive, make it easy, make it satisfying.",
    location: 450,
    color: "blue",
    importance: "Essential",
    tags: ["Productivity"],
  },

  // Thinking, Fast and Slow
  {
    id: "hl-401",
    bookId: "book-4",
    bookTitle: "Thinking, Fast and Slow",
    rawText: "System 1 operates automatically and quickly, with little or no effort and no sense of voluntary control.",
    location: 80,
    color: "yellow",
    importance: "High",
    tags: ["Cognitive Biases", "Psychology"],
  },
  {
    id: "hl-402",
    bookId: "book-4",
    bookTitle: "Thinking, Fast and Slow",
    rawText: "System 2 allocates attention to the effortful mental operations that demand it, including complex computations.",
    location: 140,
    color: "blue",
    importance: "High",
    tags: ["Cognitive Biases", "Decision Making"],
  },
  {
    id: "hl-403",
    bookId: "book-4",
    bookTitle: "Thinking, Fast and Slow",
    rawText: "We are prone to overestimate how much we understand about the world and to underestimate the role of chance.",
    location: 390,
    color: "pink",
    importance: "Essential",
    tags: ["Decision Making", "Mindset"],
  },

  // Clean Code
  {
    id: "hl-501",
    bookId: "book-5",
    bookTitle: "Clean Code",
    rawText: "Even bad code can function. But if code isn't clean, it can bring a development organization to its knees.",
    location: 95,
    color: "yellow",
    importance: "Essential",
    tags: ["Clean Code", "Software Craftsmanship"],
  },
  {
    id: "hl-502",
    bookId: "book-5",
    bookTitle: "Clean Code",
    rawText: "Leave the campground cleaner than you found it. The Boy Scout Rule.",
    location: 210,
    color: "pink",
    importance: "Essential",
    tags: ["Refactoring", "Clean Code"],
    sourceNote: "Apply incremental continuous cleanup to every PR.",
  },
];
